site_name: Libtables Documentation
pages:
  - Home: index.md
  - Concepts: concepts.md
  - Functions: functions.md
  - lt_table() display options: table_options_display.md
  - lt_table() database mutation options: table_options_database.md
theme: readthedocs
